export const ActionTypes = {
    SET_ALL_NOTES: "SET_ALL_NOTES",
    SET_SEARCHED_NOTES: "SET_SEARCHED_NOTES",
    ADD_NOTE:"ADD_NOTE",
    VIEW_LIST:"VIEW_LIST",
    UPDATE_ONE_NOTE:"UPDATE_ONE_NOTE",
    DELETE_ONE_NOTE:"DELETE_ONE_NOTE"
  };